ok

diff --git a/usercmd_updatefull b/usercmd_updatefull
--- a/usercmd_updatefull
+++ b/usercmd_updatefull
@@ -81,9 +81,9 @@ check_time_range() {
   # 检查当前时间是否在范围内
   if [[ "$current_time" > "$start_time" && "$current_time" < "$stop_time" ]]; then
     printf "\033[1;31m[STOP]\033[0m  "
-    echo -e "任务退出（$(date '+%Y-%m-%d %H:%M:%S')）：为避免与用户预设的 定时任务 冲突" | tee -a "$log_error_file"
+    echo -e "任务退出（$(date '+%Y-%m-%d %H:%M:%S')）：为避免与用户预设的 定时任务 冲突" | tee -a "$log_error_file" "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
     printf "\033[1;31m[STOP]\033[0m  "
-    echo -e "时间范围（停止建立 更新任务）：$start_time - $stop_time" | tee -a "$log_error_file"
+    echo -e "时间范围（停止建立 更新任务）：$start_time - $stop_time" | tee -a "$log_error_file" "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
     exit
   fi
 }
@@ -96,11 +96,13 @@ check_connection() {
   local log_file=$2
 
   if curl -I --connect-timeout 5 "$target" > /dev/null 2>&1; then
-    printf "\033[1;32m[OK]\033[0m 已连通 [$target] \n"
+    printf "\033[1;32m[OK]\033[0m 已连通 [$target] \n"  
+    printf " 已连通 [$target] \n"  | tee -a "$log_file" "$LOG_FULL_LAST"   "$LOG_FULL_FILE" > /dev/null  
     return 0
   else
     printf "\033[1;31m[ERROR]\033[0m" 
-    echo -e "[$target] $(date '+%Y-%m-%d %H:%M:%S') 连接失败，等待10秒后重试..." | tee -a "$log_file"
+    printf "[ERROR]"   | tee -a "$log_file" "$LOG_FULL_LAST"   "$LOG_FULL_FILE" > /dev/null  
+    echo -e "[$target] $(date '+%Y-%m-%d %H:%M:%S') 连接失败，等待10秒后重试..." | tee -a "$log_file" "$LOG_FULL_LAST"  "$LOG_FULL_FILE" 
     sleep 10
     return 1
   fi
@@ -175,49 +177,6 @@ run_command_with_show_progress() {
 
 
 
-# ---------------------------------------
-# 检测：外网是否能正常访问
-# ---------------------------------------
-
-echo -e "" >> "$LOG_ERROR_FILE"
-echo -e "-------------------------------------------------------------------" >> "$LOG_ERROR_FILE"
-echo -e "" >> "$LOG_ERROR_FILE"
-echo -e "$(date '+%Y-%m-%d %H:%M:%S')  开始测试，海外 HTTPS 连接 ..."  >> "$LOG_ERROR_FILE"
-echo -e "" >> "$LOG_ERROR_FILE"
-
-# 轮询检查网络连通性
-while true; do
-
-  # 调用检查时间范围函数
-  check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE"
-
-  # 检查 TARGET_1 的连接
-  if ! check_connection "$TARGET_1" "$LOG_ERROR_FILE"; then
-    continue # 如果连接失败，重新开始循环
-  fi
-
-  # 检查 TARGET_2 的连接
-  if ! check_connection "$TARGET_2" "$LOG_ERROR_FILE"; then
-    continue # 如果连接失败，重新开始循环
-  fi
-
-  # 检查 TARGET_3 的连接
-  if ! check_connection "$TARGET_3" "$LOG_ERROR_FILE"; then
-    continue # 如果连接失败，重新开始循环
-  fi
-
-  # 检查 TARGET_4 的连接
-  if ! check_connection "$TARGET_4" "$LOG_ERROR_FILE"; then
-    continue # 如果连接失败，重新开始循环
-  fi
-
-  # 如果N个目标，都成功连接，退出循环
-  echo -e "海外 HTTPS 连接正常 ..."
-  break
-done
-
-
-
 
 
 # -----------------------------------------------
@@ -263,16 +222,60 @@ echo -e "MacUpdater 执行日志 - $(date)" > "$LOG_MACUPDATER_FILE"
 
 
 
+# ---------------------------------------
+# 检测：外网是否能正常访问
+# ---------------------------------------
+
+echo -e "" >> "$LOG_ERROR_FILE"
+echo -e "-------------------------------------------------------------------" >> "$LOG_ERROR_FILE"
+echo -e "" >> "$LOG_ERROR_FILE"
+echo -e "【启动更新脚本】 $(date '+%Y-%m-%d %H:%M:%S')  开始测试，海外 HTTPS 连接 ..."  | tee -a "$LOG_ERROR_FILE" "$LOG_FULL_LAST"  "$LOG_FULL_FILE" 
+echo -e "===================================================================================" | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
+echo -e "" >> "$LOG_ERROR_FILE"
+
+# 轮询检查网络连通性
+while true; do
+
+  # 调用检查时间范围函数
+  check_time_range "$STOP_TIME" "$DURATION_MINUTES" "$LOG_ERROR_FILE"
+
+  # 检查 TARGET_1 的连接
+  if ! check_connection "$TARGET_1" "$LOG_ERROR_FILE"; then
+    continue # 如果连接失败，重新开始循环
+  fi
+
+  # 检查 TARGET_2 的连接
+  if ! check_connection "$TARGET_2" "$LOG_ERROR_FILE"; then
+    continue # 如果连接失败，重新开始循环
+  fi
+
+  # 检查 TARGET_3 的连接
+  if ! check_connection "$TARGET_3" "$LOG_ERROR_FILE"; then
+    continue # 如果连接失败，重新开始循环
+  fi
+
+  # 检查 TARGET_4 的连接
+  if ! check_connection "$TARGET_4" "$LOG_ERROR_FILE"; then
+    continue # 如果连接失败，重新开始循环
+  fi
+
+  # 如果N个目标，都成功连接，退出循环
+  echo -e "海外 HTTPS 连接正常 ..." | tee -a "$LOG_ERROR_FILE" "$LOG_FULL_LAST"  "$LOG_FULL_FILE" 
+  break
+done
+
+echo -e "===================================================================================" | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
+
+
+
 
 # -----------------------------------------------
 # 检查 1 ：Homebrew 是否安装（并更新）
 # -----------------------------------------------
-
-echo -e "日期：$(date '+%Y-%m-%d %H:%M:%S') ..." | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
-
+echo -e "" | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
 echo -e "" | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
 
-echo -e "===================================================================================" | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
+echo -e "日期：$(date '+%Y-%m-%d %H:%M:%S') ..." | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" > /dev/null
 
 echo -e ""                                   | tee -a "$LOG_FULL_LAST" "$LOG_FULL_FILE" 
 
